name: rise_up
description: A new Flutter project.

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  video_player: ^2.4.7
  vertical_card_pager: ^1.4.0
  sticky_headers: ^0.3.0+2
  easy_localization: ^3.0.1
  http: ^0.13.5
  intl_phone_field: ^3.1.0
  intl: ^0.17.0
  image_picker: ^0.8.6
  dotted_border: ^2.0.0+2
  checkbox_formfield: ^0.2.0
  cupertino_icons: ^1.0.2
  sizer: ^2.0.15
  flutter_svg: ^1.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - Assets/Images/
    - Assets/icons/
    - Assets/backgrounds/
    - Assets/Images/WelcomeImage/
    - Assets/lang/
    - Assets/fonts/

  fonts:
    - family: Lucida Sans
      fonts:
        - asset: Assets/fonts/l_10646.ttf
    - family: Open Sans
      fonts:
        - asset: Assets/fonts/OpenSans-Regular.ttf

Assets/Images/unsplash_-vzClPe2Yj8:
  png:
